### ISSUE TITLE
레포이름 변경

### ISSUE THREAD

**Issue by iwin2471** [colamooon/me#1]
colamooon 으로 변경하시면 깃허브 메인페이지에서 readme.md파일을 바로 볼수있어요

**Comment by colamooon** [comment]
옷 팁 감사해요~
근데 메인에 걸기엔 손발이 오그라들어서 ㅠㅠ

2020년 7월 30일 (목) 오후 12:20, Younjune Kim <notifications@github.com>님이 작성:

**Comment by colamooon** [comment]
## Gmail
dev.cucurbita@gmail.com
znznqlxk21!@T
